### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by qihaomah** [qihaomah/Becoming-a-good-developer#1]
I need some help in improving the readability of the README.md.

**Comment by BolajiOlajide** [comment]
Hey! I'd like to pick this up. Can you share more context?

**Comment by BolajiOlajide** [comment]
@qihaomah

**Comment by MaulikSS** [comment]
Hey @qihaomah ! I'd like to help with your issue :)

**Comment by nikhilpinnaparaju** [comment]
@qihaomah I've made a few edits and sent a PR. I'd like to help if there's a lot more you need help changing.

**Comment by MudraNagda** [comment]
Hey @qihaomah I'd like to help you!
